app:
  name: "gateway"
  version: "0.0.1"
server:
  host: "0.0.0.0"
  port: "4001"
postgres:
  host: "host.docker.internal"
  port: "5432"
  user: "gateway"
  password: "gateway"
  db_name: "gateway"
  ssl_mode: "disable"
jwt:
  secret: "local_secret"